.\"                                      Hey, EMACS: -*- nroff -*-
.TH ICES2 1 "July 28, 2003"
.SH NAME
ices2 \- an Ogg Vorbis broadcast streaming source client
.SH SYNOPSIS
.B ices2
.RI config.xml
.SH DESCRIPTION
\fBices2\fP is a program that connects to Icecast 2
streaming media servers, and provides them with
audio streams.  It supports both live audio input from a
soundcard and re-encoding of Ogg Vorbis files from
a playlist.
.SH OPTIONS
\fBices2\fP has no command line options.  All aspects of its
operation are controlled by the XML configuration file, whose
path is specified by the sole argument.
.SH SEE ALSO
The example configuration files, provided with the package
documentation, are the only reliable source of information
on this software.  The software is still under very active
development; detailed documentation will be written when it is
possible to do so.
.SH AUTHOR
ices2 was written by Michael Smith <msmith@icecast.org>,
Karl Heyes <karl@pts.tele2.co.uk>, and others.
.br
This manual page was written by Keegan Quinn <ice@thebasement.org>.
